name: Enchant
version: '${version}'
main: com.github.doiche.Main
api-version: '1.20'
commands:
  status:
    description: status command
  cube:
    description: cube command
  test:
    description: test command
